# Generated by Django 3.2.9 on 2022-01-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labpc',
            old_name='location',
            new_name='username',
        ),
    ]
