# Generated by Django 3.2.9 on 2022-01-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0005_alter_labpc_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='statusBoot',
            field=models.IntegerField(choices=[(0, 'Boot'), (1, 'Unboot')], default=0),
        ),
    ]
